# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fssn
description: > # this means to ignore newlines until "baseurl:"
  A minimalistic website for Francisco Soares, developer
repository: https://github.com/forbidden404
baseurl:  # the subpath of your site, e.g. /blog
url: https://forbidden404.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Francisco Soares
email: francisco.ssn94@gmail.com

navigation:
  - text: Home
    url: /
  - text: Research
    url: /research
  - text: Projects
    url: /projects

projects:
  - name: stackexchange-miner
    description: A tool to scrap the social accounts from top developers on Stack Exchange
    link: https://github.com/forbidden404/stackexchange-miner
  - name: pong
    description: A pong game written in Assembly x86 16 bits
    link: https://github.com/forbidden404/pong
  - name: rpg-project
    description: A terminal-based rpg made for a Programming 101 project.
    link: https://github.com/forbidden404/rpg-project
  - name: rpg-project-SDL
    description: A SDL2.0 version of the rpg-project using C++
    link: https://github.com/forbidden404/rpg-project-SDL
  - name: competitive-programming
    description: Repository to keep track of competitive programming answers
    link: https://github.com/forbidden404/competitive-programming
  - name: the-c-programming-language
    description: Repository to keep track of exercises from TCPL by K&R
    link: https://github.com/forbidden404/the-c-programming-language
  - name: fssn-lib
    description: A personal library of commonly used structs in C by me
    link: https://github.com/forbidden404/fssn-lib

social:
  - service: github
    username: forbidden404
    link: https://github.com/forbidden404
  - service: twitter
    username: forbidden404
    link: https://twitter.com/forbidden404

# Plugins
gems:
  - jekyll-seo-tag
