# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fssn
description: > # this means to ignore newlines until "baseurl:"
  A minimalistic website made by Francisco Soares with Jekyll.
repository: https://github.com/forbidden404
baseurl:  # the subpath of your site, e.g. /blog
url: https://forbidden404.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Francisco Soares
email: francisco.ssn94@gmail.com

navigation:
  - text: Home
    url: /
projects:
  - name: Competitive Programming
    description: A repository filled with coding challenges to practice Competitive Programming
    link: https://github.com/forbidden404/competitive-programing

social:
  - service: github
    username: forbidden404
    link: https://github.com/forbidden404
  - service: twitter
    username: forbidden404
    link: https://twitter.com/forbidden404
  - service: instagram
    username: fssn404
    link: https://instagram.com/fssn404

# Plugins
gems:
  - jekyll-seo-tag
